# Generated by Django 2.0.4 on 2018-04-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_firstname', models.CharField(max_length=50)),
                ('stud_lastname', models.CharField(max_length=50, null=True)),
                ('stud_id', models.CharField(default='000000000', max_length=9)),
                ('stud_maj', models.CharField(default='Chemistry', max_length=50)),
            ],
        ),
    ]
