# Generated by Django 2.0.4 on 2018-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=50)),
                ('course_semester', models.CharField(max_length=9)),
                ('course_year', models.CharField(max_length=9)),
            ],
        ),
    ]
