# Generated by Django 2.0.4 on 2018-04-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.CharField(default='Dr. Le', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], default='fall', max_length=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_year',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2018', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(),
        ),
    ]
