# Generated by Django 2.0.4 on 2018-04-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180413_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='fall', max_length=6),
        ),
    ]
