# Generated by Django 2.0.4 on 2018-04-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180415_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(default='', max_length=6)),
                ('course', models.CharField(default='', max_length=6)),
                ('semester', models.CharField(default='', max_length=6)),
                ('year', models.CharField(default='', max_length=6)),
                ('class_grade', models.CharField(default='', max_length=6)),
                ('lab_grade', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(default='fall', max_length=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_year',
            field=models.CharField(default='2018', max_length=4),
        ),
    ]
