# Generated by Django 2.0.4 on 2018-04-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180416_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='class_grade',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='lab_grade',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
